[package]

name = "dwemthys"
version = "0.0.1"
authors = ["jmcfarland"]
#build = "sh .build.sh"
build = "build.rs"

[dependencies]
rand = "0.2.0"

[dependencies.tcod]
git = "https://github.com/tomassedovic/tcod-rs.git"

#[dependencies.stainless]
#git = "https://github.com/reem/stainless.git"
